
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_appMoviles
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-d1nuorbipnbc73b69phg-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=am_p2_jp2z
      - DB_USERNAME=am_p2_jp2z_user
      - DB_PASSWORD=5MzWDXBCGRlpbrdHBAvyBJjp5orH7iPW


  webserver:
    image: nginx:alpine
    container_name: laravel_webservervMoviles
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: